Introduction to numpy for data analysis

In [3]:
import numpy as np

a = np.array([20,30,40])
b = np.array([60,70,80])
print(a)
print(b)
print()
print(a+b) # this will directly print the addition of the matrix, but the list will not add the 2nd list but it will concatenate
print(a*b) # this will give the multiplication of the matrix, but list will give the same list * the number of times of the given no

[20 30 40]
[60 70 80]

[ 80 100 120]
[1200 2100 3200]


In [11]:
a = np.array([40,50,'60']) # this will convert the entire array to string as it contains the element with same datatype
print(a) # if there is float in the array then it will convert the entire array to an float

['40' '50' '60']
