In [4]:
import numpy as np
arr1 = np.array([[30,40],[20,10]])
arr2 = np.array([[30,20],[10,20]])
print(f"array 1 is {arr1}")
print(f"array 2 is {arr2}")
print(f"The sum of the both the array is {arr1+arr2}")

# using function
print(np.add(arr1,arr2))


array 1 is [[30 40]
 [20 10]]
array 2 is [[30 20]
 [10 20]]
The sum of the both the array is [[60 60]
 [30 30]]
[[60 60]
 [30 30]]


In [5]:
import numpy as np
arr1 = np.array([[30,40],[20,10]])
arr2 = np.array([[30,20],[10,20]])
print(arr1-arr2)
print(np.subtract(arr1,arr2))

[[  0  20]
 [ 10 -10]]
[[  0  20]
 [ 10 -10]]


In [6]:
# multiply fucntion
import numpy as np
arr1 = np.array([[30,40],[20,10]])
arr2 = np.array([[30,20],[10,20]])
print(arr1*arr2)
print(np.multiply(arr1,arr2))

[[900 800]
 [200 200]]
[[900 800]
 [200 200]]


In [7]:
# divide function
import numpy as np
arr1 = np.array([[30,40],[20,10]])
arr2 = np.array([[30,20],[10,20]])
print(arr1/arr2)
print(np.divide(arr1,arr2))

[[1.  2. ]
 [2.  0.5]]
[[1.  2. ]
 [2.  0.5]]


In [8]:
# power function
import numpy as np
arr1 = np.array([3,4,5,6])
arr2 = np.array([2])
print(np.power(arr1,arr2))

[ 9 16 25 36]
