In [1]:
# Contatenate 
import numpy as np
arr1 = np.array([[30,40],[50,10]])
arr2 = np.array([[5,5],[3,2]])
print(np.concatenate([arr1,arr2]))

[[30 40]
 [50 10]
 [ 5  5]
 [ 3  2]]


In [2]:
print(np.concatenate([arr1,arr2], axis = 1))

# Axis 0: Refers to the rows (or the first dimension). When performing operations along axis=0, NumPy will operate down the rows.
# Axis 1: Refers to the columns (or the second dimension). When performing operations along axis=1, NumPy will operate across the columns.

[[30 40  5  5]
 [50 10  3  2]]


In [8]:
print(np.hstack([arr1,arr2])) # horizontal concatenation

[[30 40  5  5]
 [50 10  3  2]]


In [10]:
print(np.vstack([arr1, arr2])) # vertical contatenation

[[30 40]
 [50 10]
 [ 5  5]
 [ 3  2]]


In [15]:
# splitting the values of an array
a = np.array([20,30,40,50,60])
b = np.array_split(a,3) # splitting array into 3 subarrays
c = np.array_split(a,4) # splitting array into 4 parts
print(b)
print(b[1]) # printing the first part of an array
print(c)

[array([20, 30]), array([40, 50]), array([60])]
[40 50]
[array([20, 30]), array([40]), array([50]), array([60])]
