In [ ]:
''' np.append(h,g) - append items to an array
    np.insert(a,1,5) - insert item in an array
    np.delete(a,[1]) - delete items from an array'''

In [1]:
import numpy as np

a = np.array([[20,40],[60,80]])
print(np.append(a,[90,100])) # it will first convert the 2d array into 1d and then add the values to it


[ 20  40  60  80  90 100]


In [4]:
print(np.insert(a,1,[50,60], axis = 1)) # numpy will operate across colums and insert the elements to the 2nd index

[[20 50 40]
 [60 60 80]]


In [5]:
print(np.insert(a,1,[50,60], axis = 0)) # numpy wil operate across rows and insert the elements to 2nd position

[[20 40]
 [50 60]
 [60 80]]


In [12]:
# delete
print(a)
print()
print(np.delete(a,1)) # it will convert a to 1d array and delete element at index 1
print()
print(np.delete(a,1,axis = 0))
print()
print(np.delete(a,1,axis = 1))

[[20 40]
 [60 80]]

[20 60 80]

[[20 40]]

[[20]
 [60]]
