In [5]:
import numpy as np

# sorting an array
ar = np.array([4,6,3,8,7,1])
arr = np.array([[2,5,3,6,],[3,1,7,4,]])
print(np.sort(ar)) # sorts the array in ascending order
print(np.sort(arr)) # this will sort both the rows of 2d arrays in ascending order


[1 3 4 6 7 8]
[[2 3 5 6]
 [1 3 4 7]]


In [8]:
s = np.where(ar == 4) # gives index having 4 
d = np.where(ar % 2 == 0) # gives indexes where element is divisible by 2
print(s)
print(d)

sort = np.sort(ar)
ss = np.searchsorted(sort, 3)
print(ss)


(array([0], dtype=int64),)
(array([0, 1, 3], dtype=int64),)
1


In [14]:
# filter 
ar = np.array([20,30,40,50,60])
fa = ar>35
new = ar[fa]
print(new)

# printing even values using filter
f = [True,False,True,False,True]
n = ar[f]
print(n)

d = ar%2 == 0
e = ar[d]
print(e)

[40 50 60]
[20 40 60]
[20 30 40 50 60]
