In [13]:
import numpy as np

a = np.array([20,30,40,50])
b = np.array([30,80,70,10])

print(np.sum(a))
print(np.min(a))
print(np.max(a))
print(np.size(a))
print(np.shape(a))
print(np.mean(a))
print(np.cumsum(a)) # gives the cumulative sum of the elements
print(np.cumprod([a,b], axis= 0)) # this will give cumulative product across rows
print()
print(np.cumprod([a,b], axis= 1)) # this will give cumulative product across columns

140
20
50
4
(4,)
35.0
[ 20  50  90 140]
[[  20   30   40   50]
 [ 600 2400 2800  500]]

[[     20     600   24000 1200000]
 [     30    2400  168000 1680000]]


In [19]:
a = [100,150,199,200,250,130]
b = [10,50,30,40,30,10]

price = np.array(a)
quantity = np.array(b)

print(price, "\n", quantity)
print()
c = np.cumprod([price,quantity], axis = 0) # second row of this will give the total revenue i.e price * quantity
print(c)
print()
print(c[1].sum()) # give the sum of the total revenue i.e sum of price*quantity


[100 150 199 200 250 130] 
 [10 50 30 40 30 10]

[[ 100  150  199  200  250  130]
 [1000 7500 5970 8000 7500 1300]]

31270
